services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api/afisha
        VITE_CDN_URL: /content/afisha
    container_name: frontend
    restart: always
    volumes:
      - frontend-dist:/app/dist
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: prac
      DATABASE_PASSWORD: 2706
      DATABASE_NAME: prac
    restart: always
    volumes:
      - ./backend/public/content/afisha:/app/public/content/afisha
    networks:
      - webnet

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: 2706
      POSTGRES_DB: prac
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - webnet
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
  frontend-dist:

networks:
  webnet:
